function [BW] = blueDetection(RGB)
%createMask  Threshold RGB image using auto-generated code from colorThresholder app.
%  [BW,MASKEDRGBIMAGE] = createMask(RGB) thresholds image RGB using
%  auto-generated code from the colorThresholder App. The colorspace and
%  minimum/maximum values for each channel of the colorspace were set in the
%  App and result in a binary mask BW and a composite image maskedRGBImage,
%  which shows the original RGB image values under the mask BW.

% Auto-generated by colorThresholder app on 07-Nov-2016
%------------------------------------------------------


% Convert RGB image to chosen color space
RGB = im2double(RGB);
cform = makecform('srgb2lab', 'AdaptedWhitePoint', whitepoint('D65'));
I = applycform(RGB,cform);

% % Define thresholds for channel 1 based on histogram settings
% channel1Min = 17.637;
% channel1Max = 55.308;
% 
% % Define thresholds for channel 2 based on histogram settings
% channel2Min = 6.742;
% channel2Max = 31.663;
% 
% % Define thresholds for channel 3 based on histogram settings
% channel3Min = -41.185;
% channel3Max = -15.037;


% % Define thresholds for channel 1 based on histogram settings
% channel1Min = 0.000;
% channel1Max = 39.555;
% 
% % Define thresholds for channel 2 based on histogram settings
% channel2Min = 2.890;
% channel2Max = 26.101;
% 
% % Define thresholds for channel 3 based on histogram settings
% channel3Min = -39.637;
% channel3Max = -14.964;

%Rolling_06
% % Define thresholds for channel 1 based on histogram settings
% channel1Min = 0.020;
% channel1Max = 100.000;
% 
% % Define thresholds for channel 2 based on histogram settings
% channel2Min = 10.467;
% channel2Max = 29.523;
% 
% % Define thresholds for channel 3 based on histogram settings
% channel3Min = -60.509;
% channel3Max = -18.823;

% Define thresholds for channel 1 based on histogram settings
channel1Min = 0.000;
channel1Max = 100.000;

% Define thresholds for channel 2 based on histogram settings
channel2Min = 5.395;
channel2Max = 32.942;

% Define thresholds for channel 3 based on histogram settings
channel3Min = -56.733;
channel3Max = -24.028;

% Create mask based on chosen histogram thresholds
BW = (I(:,:,1) >= channel1Min ) & (I(:,:,1) <= channel1Max) & ...
    (I(:,:,2) >= channel2Min ) & (I(:,:,2) <= channel2Max) & ...
    (I(:,:,3) >= channel3Min ) & (I(:,:,3) <= channel3Max);

